### ISSUE TITLE
why not use TORCH.CUDA.AMP

### ISSUE THREAD

**Issue by JunMa11** [Alibaba-MIIL/Solving_ImageNet#2]
Thanks for the awesome work.

It seems that amp is based on this old repo: https://github.com/NVIDIA/apex.

https://github.com/Alibaba-MIIL/Solving_ImageNet/blob/7eb8e3b17f595eb42b7e80f70ef799b9af0f43a8/train.py#L45-L50

However, this repo is error-prone when installing on the cluster and torch has supported amp https://pytorch.org/docs/stable/amp.html

Would it be possible to only use the [torch.cuda.amp](https://pytorch.org/docs/stable/amp.html#module-torch.cuda.amp) and remove the dependency of [NVIDIA/apex](https://github.com/NVIDIA/apex.)?

**Comment by mrT23** [comment]
further read the code. It eventually uses [torch.cuda.amp](https://pytorch.org/docs/stable/amp.html#module-torch.cuda.amp) for training

```
has_native_amp = False
try:
    if getattr(torch.cuda.amp, 'autocast') is not None:
        has_native_amp = True
except AttributeError:
    pass
```

p.s. the training code is a modified version of [timm repo](https://github.com/rwightman/pytorch-image-models). this specific amp logic was not written by me

**Comment by JunMa11** [comment]
Thanks for your help very much:)
