### ISSUE TITLE
Scripts to measure speed on GPU & CPU devices

### ISSUE THREAD

**Issue by mmaaz60** [Alibaba-MIIL/Solving_ImageNet#3]
Hi Authors,

Thanks for sharing the great work. I would like to ask if there is any plan of releasing scripts measuring inference FPS on CPU & GPU devices. That will include the scripts for batch norm fusion, converting the models in OpenVino format, etc. It would be of great help.

Thank you

**Comment by mrT23** [comment]
Hi mmaaz

we are using the script for bn fusion also during training (for the KD teachers):
https://github.com/Alibaba-MIIL/Solving_ImageNet/blob/7eb8e3b17f595eb42b7e80f70ef799b9af0f43a8/kd/kd_utils.py#L21

regarding scripts to measure inference times, we do want to release them, but it will take some time. we plan to add also TensorRT measurements.

Tal
